buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '5.1.+'
}

repositories {
    maven { url = 'https://maven.minecraftforge.net' }
    mavenCentral()
}

version = '1.0.0'
group = 'com.yourname.harrypottermod'
archivesBaseName = 'harrypottermod'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.19.2'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                harrypottermod {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                harrypottermod {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        name = 'Maven'
        url = 'https://maven.minecraftforge.net'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.19.2-43.3.0'
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "harrypottermod",
                "Specification-Vendor"   : "yourname",
                "Specification-Version"  : "1",
                "Implementation-Title"   : project.name,
                "Implementation-Version" : "${version}",
                "Implementation-Vendor"  : "yourname",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}